print("hai cantik")
print("jangan lupa makan")
print("jangan lupa istirahat")
print("mainya jangan jauh jauh")
print("hati hati di jalan")
print("bole kenalan ga")
print("selamat ulang tahun")
print("selamat pagi")
print("selamat malam")
print("bismillah sukses")